name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@v14

      - name: Enable Nix cache (magic-nix-cache)
        uses: https://github.com/DeterminateSystems/magic-nix-cache-action@v8

      - name: Build
        run: nix build . --print-build-logs

      - name: Test
        run: echo 'No tests yet - see ticket #1'

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kbai
          path: ./result/bin/kbai
          retention-days: 7

  release:
    runs-on: ci
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@v14

      - name: Enable Nix cache (magic-nix-cache)
        uses: https://github.com/DeterminateSystems/magic-nix-cache-action@v8

      - name: Build release binary
        run: nix build . --print-build-logs

      - name: Publish release
        uses: actions/forgejo-release@v2.5.0
        with:
          direction: upload
          token: ${{ secrets.GITHUB_TOKEN }}
          release-dir: ./result/bin/
          release-notes-assistant: true
          override: true
